version: '3.9'

services:
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_DB: SanLuis
      POSTGRES_USER: zennon
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 102426
    ports:
      - "5050:80"
